import type { User, Book, BorrowRecord, Material } from './types'

export const INITIAL_USERS: User[] = [
  {
    id: 'admin-1',
    name: 'Dr. Priya Sharma',
    email: 'admin@library.edu',
    password: 'admin123',
    role: 'admin',
    phone: '+91 98765 43210',
    joinDate: '2020-06-01',
  },
  {
    id: 'u-1',
    name: 'Arjun Mehta',
    email: 'arjun@student.edu',
    password: 'student123',
    role: 'user',
    rollNumber: 'CS21001',
    department: 'Computer Science',
    year: 3,
    semester: 5,
    phone: '+91 87654 32109',
    joinDate: '2021-08-15',
  },
  {
    id: 'u-2',
    name: 'Sneha Patel',
    email: 'sneha@student.edu',
    password: 'student123',
    role: 'user',
    rollNumber: 'EC21045',
    department: 'Electronics',
    year: 2,
    semester: 4,
    phone: '+91 76543 21098',
    joinDate: '2022-08-10',
  },
  {
    id: 'u-3',
    name: 'Rohan Gupta',
    email: 'rohan@student.edu',
    password: 'student123',
    role: 'user',
    rollNumber: 'ME20032',
    department: 'Mechanical',
    year: 4,
    semester: 7,
    phone: '+91 65432 10987',
    joinDate: '2020-08-12',
  },
  {
    id: 'u-4',
    name: 'Ananya Singh',
    email: 'ananya@student.edu',
    password: 'student123',
    role: 'user',
    rollNumber: 'CE22015',
    department: 'Civil Engineering',
    year: 1,
    semester: 2,
    phone: '+91 54321 09876',
    joinDate: '2023-08-20',
  },
]

export const INITIAL_BOOKS: Book[] = [
  {
    id: 'b-1',
    title: 'Introduction to Algorithms',
    author: 'Cormen, Leiserson, Rivest & Stein',
    isbn: '978-0262033848',
    category: 'Computer Science',
    totalCopies: 5,
    availableCopies: 2,
    description: 'The definitive guide to algorithms. Covers sorting, graph algorithms, dynamic programming, and much more.',
    publishYear: 2009,
    publisher: 'MIT Press',
    location: 'CS-A-12',
    coverAccent: '#1e3a5f',
  },
  {
    id: 'b-2',
    title: 'Clean Code',
    author: 'Robert C. Martin',
    isbn: '978-0132350884',
    category: 'Software Engineering',
    totalCopies: 4,
    availableCopies: 1,
    description: 'A handbook of agile software craftsmanship. Learn to write readable, maintainable, and clean code.',
    publishYear: 2008,
    publisher: 'Prentice Hall',
    location: 'SE-B-05',
    coverAccent: '#1a1a2e',
  },
  {
    id: 'b-3',
    title: 'Operating System Concepts',
    author: 'Silberschatz, Galvin & Gagne',
    isbn: '978-1119800361',
    category: 'Computer Science',
    totalCopies: 6,
    availableCopies: 4,
    description: 'Comprehensive coverage of OS fundamentals including processes, memory management, and file systems.',
    publishYear: 2018,
    publisher: 'Wiley',
    location: 'CS-A-08',
    coverAccent: '#2d6a4f',
  },
  {
    id: 'b-4',
    title: 'Database System Concepts',
    author: 'Silberschatz, Korth & Sudarshan',
    isbn: '978-0073523323',
    category: 'Computer Science',
    totalCopies: 5,
    availableCopies: 5,
    description: 'Standard textbook covering relational databases, SQL, normalization, and transaction management.',
    publishYear: 2019,
    publisher: 'McGraw-Hill',
    location: 'CS-C-02',
    coverAccent: '#6b2737',
  },
  {
    id: 'b-5',
    title: 'Engineering Mathematics',
    author: 'B.S. Grewal',
    isbn: '978-8174091955',
    category: 'Mathematics',
    totalCopies: 8,
    availableCopies: 3,
    description: 'Covers differential equations, linear algebra, calculus, and numerical methods for engineers.',
    publishYear: 2020,
    publisher: 'Khanna Publishers',
    location: 'MA-D-01',
    coverAccent: '#7b4f12',
  },
  {
    id: 'b-6',
    title: 'Signals and Systems',
    author: 'Oppenheim & Willsky',
    isbn: '978-0138147570',
    category: 'Electronics',
    totalCopies: 4,
    availableCopies: 2,
    description: 'Covers continuous and discrete time signals, Fourier transforms, Laplace and Z-transforms.',
    publishYear: 2013,
    publisher: 'Pearson',
    location: 'EC-B-10',
    coverAccent: '#4a3728',
  },
  {
    id: 'b-7',
    title: 'Strength of Materials',
    author: 'R.K. Bansal',
    isbn: '978-8131808146',
    category: 'Mechanical',
    totalCopies: 6,
    availableCopies: 6,
    description: 'Covers stress-strain relationships, bending, torsion, deflection of beams, and column design.',
    publishYear: 2010,
    publisher: 'Laxmi Publications',
    location: 'ME-E-03',
    coverAccent: '#2c3e50',
  },
  {
    id: 'b-8',
    title: 'Artificial Intelligence: A Modern Approach',
    author: 'Stuart Russell & Peter Norvig',
    isbn: '978-0134610993',
    category: 'Computer Science',
    totalCopies: 3,
    availableCopies: 0,
    description: 'Leading AI textbook. Covers search, knowledge representation, planning, learning, and uncertainty.',
    publishYear: 2020,
    publisher: 'Pearson',
    location: 'CS-A-20',
    coverAccent: '#16213e',
  },
  {
    id: 'b-9',
    title: 'Computer Networks',
    author: 'Andrew S. Tanenbaum',
    isbn: '978-0132126953',
    category: 'Computer Science',
    totalCopies: 5,
    availableCopies: 3,
    description: 'Comprehensive coverage of networking protocols, TCP/IP, wireless networks, and security.',
    publishYear: 2010,
    publisher: 'Pearson',
    location: 'CS-B-15',
    coverAccent: '#4a5568',
  },
  {
    id: 'b-10',
    title: 'Fluid Mechanics',
    author: 'Frank M. White',
    isbn: '978-0073398273',
    category: 'Mechanical',
    totalCopies: 4,
    availableCopies: 2,
    description: 'Covers fluid statics, dynamics, viscous flow, boundary layers, and turbomachinery.',
    publishYear: 2015,
    publisher: 'McGraw-Hill',
    location: 'ME-E-07',
    coverAccent: '#2e4057',
  },
  {
    id: 'b-11',
    title: 'Digital Electronics',
    author: 'Morris Mano & Michael Ciletti',
    isbn: '978-0132091893',
    category: 'Electronics',
    totalCopies: 6,
    availableCopies: 4,
    description: 'Covers logic circuits, Boolean algebra, combinational and sequential circuit design.',
    publishYear: 2012,
    publisher: 'Pearson',
    location: 'EC-A-05',
    coverAccent: '#3d405b',
  },
  {
    id: 'b-12',
    title: 'Concrete Technology',
    author: 'M.S. Shetty',
    isbn: '978-8121901604',
    category: 'Civil Engineering',
    totalCopies: 4,
    availableCopies: 4,
    description: 'Properties of concrete, mix design, durability, testing, and quality control methods.',
    publishYear: 2005,
    publisher: 'S. Chand',
    location: 'CE-F-02',
    coverAccent: '#5c4033',
  },
]

export const INITIAL_BORROWS: BorrowRecord[] = [
  {
    id: 'br-1',
    userId: 'u-1',
    bookId: 'b-1',
    issueDate: '2026-06-01',
    dueDate: '2026-06-15',
    returnDate: '2026-06-14',
    status: 'returned',
    fine: 0,
    finePaid: true,
    issuedBy: 'admin-1',
  },
  {
    id: 'br-2',
    userId: 'u-1',
    bookId: 'b-8',
    issueDate: '2026-06-20',
    dueDate: '2026-07-04',
    status: 'overdue',
    fine: 130,
    finePaid: false,
    issuedBy: 'admin-1',
  },
  {
    id: 'br-3',
    userId: 'u-2',
    bookId: 'b-3',
    issueDate: '2026-07-01',
    dueDate: '2026-07-15',
    returnDate: '2026-07-14',
    status: 'returned',
    fine: 0,
    finePaid: true,
    issuedBy: 'admin-1',
  },
  {
    id: 'br-4',
    userId: 'u-3',
    bookId: 'b-5',
    issueDate: '2026-07-16',
    dueDate: '2026-08-01',
    status: 'active',
    fine: 0,
    finePaid: false,
    issuedBy: 'admin-1',
  },
  {
    id: 'br-5',
    userId: 'u-1',
    bookId: 'b-9',
    issueDate: '2026-07-20',
    dueDate: '2026-08-03',
    status: 'active',
    fine: 0,
    finePaid: false,
    issuedBy: 'admin-1',
  },
  {
    id: 'br-6',
    userId: 'u-2',
    bookId: 'b-6',
    issueDate: '2026-06-10',
    dueDate: '2026-06-24',
    status: 'overdue',
    fine: 180,
    finePaid: false,
    issuedBy: 'admin-1',
  },
  {
    id: 'br-7',
    userId: 'u-4',
    bookId: 'b-12',
    issueDate: '2026-07-22',
    dueDate: '2026-08-05',
    status: 'active',
    fine: 0,
    finePaid: false,
    issuedBy: 'admin-1',
  },
  {
    id: 'br-8',
    userId: 'u-3',
    bookId: 'b-2',
    issueDate: '2026-07-01',
    dueDate: '2026-07-15',
    returnDate: '2026-07-13',
    status: 'returned',
    fine: 0,
    finePaid: true,
    issuedBy: 'admin-1',
  },
]

export const INITIAL_MATERIALS: Material[] = [
  {
    id: 'm-1',
    title: 'Data Structures — Complete Notes',
    subject: 'Data Structures & Algorithms',
    year: 2,
    semester: 3,
    fileType: 'PDF',
    fileSize: '4.2 MB',
    uploadDate: '2026-06-15',
    description: 'Complete notes covering arrays, linked lists, trees, graphs, and sorting algorithms.',
  },
  {
    id: 'm-2',
    title: 'Digital Electronics Lab Manual',
    subject: 'Digital Electronics',
    year: 2,
    semester: 4,
    fileType: 'PDF',
    fileSize: '8.7 MB',
    uploadDate: '2026-05-20',
    description: 'Lab experiments for logic gates, flip-flops, counters, and shift registers.',
  },
  {
    id: 'm-3',
    title: 'Engineering Thermodynamics Slides',
    subject: 'Thermodynamics',
    year: 2,
    semester: 3,
    fileType: 'PPT',
    fileSize: '12.1 MB',
    uploadDate: '2026-06-01',
    description: 'Lecture slides covering thermodynamics laws, cycles, and heat transfer applications.',
  },
  {
    id: 'm-4',
    title: 'DBMS — Complete Study Notes',
    subject: 'Database Management Systems',
    year: 3,
    semester: 5,
    fileType: 'PDF',
    fileSize: '6.3 MB',
    uploadDate: '2026-06-28',
    description: 'Comprehensive notes on ER diagrams, SQL, normalization, and ACID transactions.',
  },
  {
    id: 'm-5',
    title: 'OS Previous Year Papers (2021–2026)',
    subject: 'Operating Systems',
    year: 3,
    semester: 5,
    fileType: 'PDF',
    fileSize: '3.1 MB',
    uploadDate: '2026-07-10',
    description: 'Past 5 years examination papers with complete solutions for Operating Systems.',
  },
  {
    id: 'm-6',
    title: 'Machine Learning — Introduction',
    subject: 'Machine Learning',
    year: 4,
    semester: 7,
    fileType: 'PDF',
    fileSize: '9.4 MB',
    uploadDate: '2026-05-15',
    description: 'Supervised and unsupervised learning, neural networks, and model evaluation.',
  },
  {
    id: 'm-7',
    title: 'Structural Analysis Notes',
    subject: 'Structural Analysis',
    year: 3,
    semester: 6,
    fileType: 'PDF',
    fileSize: '5.8 MB',
    uploadDate: '2026-06-05',
    description: 'Complete notes on beams, frames, arches, influence lines, and matrix methods.',
  },
  {
    id: 'm-8',
    title: 'Signals & Systems — Formula Sheet',
    subject: 'Signals and Systems',
    year: 3,
    semester: 5,
    fileType: 'PDF',
    fileSize: '1.2 MB',
    uploadDate: '2026-07-15',
    description: 'Quick-reference formula sheet for Fourier, Laplace, and Z-transforms.',
  },
  {
    id: 'm-9',
    title: 'Engineering Mathematics Unit 1–4',
    subject: 'Engineering Mathematics',
    year: 1,
    semester: 1,
    fileType: 'PDF',
    fileSize: '7.6 MB',
    uploadDate: '2026-06-20',
    description: 'First-year maths notes covering matrices, differential calculus, and integration.',
  },
  {
    id: 'm-10',
    title: 'Computer Networks Lab Programs',
    subject: 'Computer Networks',
    year: 4,
    semester: 7,
    fileType: 'DOC',
    fileSize: '2.4 MB',
    uploadDate: '2026-07-05',
    description: 'Socket programming labs: TCP/UDP client-server, HTTP, and DNS implementations.',
  },
  {
    id: 'm-11',
    title: 'Applied Physics Notes',
    subject: 'Applied Physics',
    year: 1,
    semester: 2,
    fileType: 'PDF',
    fileSize: '5.0 MB',
    uploadDate: '2026-07-18',
    description: 'Optics, semiconductor physics, magnetic materials, and superconductivity.',
  },
  {
    id: 'm-12',
    title: 'Control Systems — Complete Guide',
    subject: 'Control Systems',
    year: 3,
    semester: 6,
    fileType: 'PDF',
    fileSize: '6.9 MB',
    uploadDate: '2026-07-02',
    description: 'Transfer functions, Bode plots, root locus, Nyquist stability, and PID controllers.',
  },
]
